M48
; DRILL file KiCad 10.0.1 date 2026-06-17T19:14:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-17T19:14:15+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X128.58Y-107.0
X133.18Y-107.0
T2
X119.6Y-108.0
X119.6Y-146.8
X142.2Y-108.0
X142.2Y-146.8
M30
